apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dex-k8s-authenticator.fullname" . }}
  labels:
    app: {{ template "dex-k8s-authenticator.fullname" . }}
    env: {{ default "dev" .Values.global.deployEnv }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  credentials: {{ default "" .Values.dex-core.client_secret | b64enc }}